### ISSUE TITLE
在设置选项里选了使用内建AI服务 (Provided API）后，切换到其他标签再切换回来设置页面缺省显示使用自定API的画面

### ISSUE THREAD

**Issue by Dolyn157** [guiiapp/guii-devtools#4]
在设置选项里选了使用内建AI服务 (Provided API）后，切换到其他标签再切换回来设置页面缺省显示使用自定API的画面,情况如下图所示。但是实际 Local Storage 里面储存的相关参数是对的。
![image](https://github.com/user-attachments/assets/77dfab1d-e3b9-4f05-8276-2c7b00882f53)

**Comment by Dustella** [comment]
fixed in [`v0.7.5`](https://www.npmjs.com/package/@guiiai/core/v/0.7.5), please update.
